version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config.properties
    image: 637423396561.dkr.ecr.us-east-1.amazonaws.com/iotplusplus/conductor:1.3
    container_name: conductor-server
    networks:
      - internal
    ports:
      - 8080:8080
      - 5000:5000
    healthcheck:
      test: [ "CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health" ]
      interval: 60s
      timeout: 30s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
volumes:
  pgdata-conductor:
    driver: local

networks:
  internal:
